-- Run this once in Supabase: Project → SQL Editor → New query → paste → Run

create table if not exists interviews (
  id uuid primary key default gen_random_uuid(),
  conversation_id text unique not null,
  agent_id text,
  project_name text,
  duration_seconds integer,

  -- structured answers extracted by our own finalize step (lib/analyze.js)
  favorite_part text,
  tricky_part text,
  what_youd_change text,
  pride_level text,
  would_build_again boolean,
  would_build_again_reason text,

  -- generated by our own analysis pass (lib/analyze.js)
  summary text,
  key_insights text,
  improvement_suggestions text,
  overall_sentiment text,

  -- raw data, kept for reference / re-analysis later
  full_transcript jsonb,
  raw_data_collection jsonb,

  created_at timestamptz not null default now()
);

create index if not exists interviews_project_name_idx on interviews (project_name);
create index if not exists interviews_created_at_idx on interviews (created_at desc);

-- Row Level Security: locked down by default. The app only ever writes
-- via the service_role key (server-side, in /api/turn), which bypasses
-- RLS, so this just prevents any public/anon access.
alter table interviews enable row level security;
